FROM python:3.6.7-stretch

# Install required packages
RUN apt-get update && \
    apt-get install -y \
    libsasl2-dev \
    python-dev \
    libldap2-dev \
    libssl-dev &&\
    rm -rf /var/lib/apt/lists/*

# Set workdir and install python requirements
WORKDIR /usr/src/love
COPY manager/requirements.txt .
RUN pip install -r requirements.txt

# Expose static files and port
EXPOSE 8000

# Set env variables for runtime (to be replaced in docker-cpomse files)
ENV ADMIN_USER_PASS=test
ENV USER_USER_PASS=test
ENV CMD_USER_PASS=test

# Run development server in runtime
ENTRYPOINT ["./runserver-dev.sh"]
