# Generated by Django 2.1.7 on 2019-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
    ]
