# Generated by Django 2.1.7 on 2019-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190528_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True, verbose_name='Key'),
        ),
    ]
