# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 2.1.7 on 2019-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20190528_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                unique=True,
                verbose_name="Key",
            ),
        ),
    ]
