# Generated by Django 2.1.10 on 2019-07-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globalpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'managed': False, 'permissions': (('command.execute_command', 'Execute Commands'), ('command.run_script', 'Run and Requeue scripts in ScriptQueues'))},
        ),
    ]
