# Generated by Django 3.0.7 on 2020-12-28 23:34

import django.db.models.deletion
import manager.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_auto_20190722_1622"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation time"),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("file_name", models.CharField(blank=True, max_length=30)),
                (
                    "config_file",
                    models.FileField(
                        default="configs/default.json",
                        upload_to="configs/",
                        validators=[manager.utils.validate_file_extension],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
