# Generated by Django 3.0.14 on 2021-07-30 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_emergencycontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermissions",
            options={
                "managed": False,
                "permissions": (
                    ("command.execute_command", "Execute Commands"),
                    ("command.run_script", "Run and Requeue scripts in ScriptQueues"),
                    ("authlist.administrator", "Access and resolve AuthList requests"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CSCNonAuthorizedCSC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("target_csc", models.CharField(max_length=100)),
                ("blocked_csc", models.CharField(max_length=100)),
            ],
            options={
                "permissions": (("administrator", "Administrate the AuthList"),),
                "unique_together": {("target_csc", "blocked_csc")},
            },
        ),
        migrations.CreateModel(
            name="CSCAuthorizedUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("target_csc", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("hostname", models.CharField(max_length=100)),
            ],
            options={
                "permissions": (("administrator", "Administrate the AuthList"),),
                "unique_together": {("target_csc", "username", "hostname")},
            },
        ),
        migrations.CreateModel(
            name="CSCAuthorizationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_csc", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("hostname", models.CharField(max_length=100)),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested at"
                    ),
                ),
                ("blocked_cscs", models.CharField(blank=True, max_length=200)),
                (
                    "restriction_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Restriction duration (seconds)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Authorized", "Authorized"),
                            ("Denied", "Denied"),
                            ("Reverted", "Reverted"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "reverted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reverted at"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reverted by",
                    ),
                ),
            ],
        ),
    ]
