# Generated by Django 3.1.14 on 2022-07-05 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0008_auto_20211125_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="configfile",
            name="selected_by_users",
            field=models.ManyToManyField(related_name="selected_config_file", to=settings.AUTH_USER_MODEL),
        ),
    ]
