# Generated by Django 3.1.14 on 2022-09-14 15:42

import manager.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_configfile_selected_by_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfile",
            name="config_file",
            field=models.FileField(
                default="configs/default.json",
                upload_to="configs/",
                validators=[
                    manager.utils.validate_file_extension,
                    manager.utils.validate_json_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configfile",
            name="selected_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_config_file",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
