# Generated by Django 3.1.14 on 2022-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_configfile_selected_by_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
            ],
            options={"abstract": False,},
        ),
    ]
