# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.14 on 2022-09-14 15:42

import manager.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_configfile_selected_by_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfile",
            name="config_file",
            field=models.FileField(
                default="configs/default.json",
                upload_to="configs/",
                validators=[
                    manager.utils.validate_file_extension,
                    manager.utils.validate_json_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configfile",
            name="selected_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_config_file",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
