# Generated by Django 3.1.14 on 2022-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_configfile_selected_by_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="cscauthorizationrequest",
            name="execution_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cscauthorizationrequest",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("Successful", "Successful"),
                    ("Fail", "Fail"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="authorized_users",
            field=models.TextField(
                blank=True,
                help_text="Please use the following format: <em>+user@host,-user@host</em>.\
                Spaces are allowed after commas.",
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="cscs_to_change",
            field=models.TextField(
                help_text="Please use the following format: <em>ATDome:0,ScriptQueue:1</em>.\
                Spaces are allowed after commas."
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="unauthorized_cscs",
            field=models.TextField(
                blank=True,
                help_text="Please use the following format: <em>+ATPtg:0,-ScriptQueue:2</em>.\
                Spaces are allowed after commas.",
            ),
        ),
    ]
