# Generated by Django 3.1.14 on 2022-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_configfile_selected_by_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="cscauthorizationrequest",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("Successful", "Successful"),
                    ("Fail", "Fail"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
