# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.14 on 2022-11-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_auto_20220914_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="cscauthorizationrequest",
            name="execution_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cscauthorizationrequest",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("Successful", "Successful"),
                    ("Fail", "Fail"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="authorized_users",
            field=models.TextField(
                blank=True,
                help_text="Please use the following format: <em>+user@host,-user@host</em>."
                " Spaces are allowed after commas.",
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="cscs_to_change",
            field=models.TextField(
                help_text="Please use the following format: <em>ATDome:0,ScriptQueue:1</em>."
                " Spaces are allowed after commas."
            ),
        ),
        migrations.AlterField(
            model_name="cscauthorizationrequest",
            name="unauthorized_cscs",
            field=models.TextField(
                blank=True,
                help_text="Please use the following format: <em>+ATPtg:0,-ScriptQueue:2</em>."
                " Spaces are allowed after commas.",
            ),
        ),
    ]
