# Generated by Django 3.1.14 on 2022-09-28 18:34

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_imagetag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfile",
            name="config_file",
            field=models.FileField(
                default="configs/default.json",
                upload_to="configs/",
                validators=[
                    api.models.ConfigFile.validate_file_extension,
                    api.models.ConfigFile.validate_json_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configfile",
            name="selected_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_config_file",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
