# Generated by Django 3.1.14 on 2023-05-08 15:11

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_controllocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfile",
            name="config_file",
            field=models.FileField(
                max_length=200,
                upload_to="configs/",
                validators=[
                    api.models.ConfigFile.validate_file_extension,
                    api.models.ConfigFile.validate_json_file,
                ],
            ),
        ),
    ]
