# Generated by Django 3.1.14 on 2023-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_auto_20230508_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_path", models.CharField(max_length=100)),
                ("config_name", models.CharField(max_length=50)),
                ("config_schema", models.TextField()),
                (
                    "script_type",
                    models.CharField(
                        choices=[("standard", "standard"), ("external", "external")],
                        default=None,
                        max_length=10,
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
