# Generated by Django 3.1.14 on 2023-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_scriptconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedScriptMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_salindex", models.CharField(max_length=100)),
                ("script_execution_time", models.IntegerField()),
                ("script_configuration", models.TextField()),
            ],
        ),
    ]
