# Generated by Django 3.1.14 on 2023-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_scriptconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllocation",
            name="ip_whitelist",
            field=models.TextField(blank=True),
        ),
    ]
