# Generated by Django 3.1.14 on 2024-05-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_controllocation_ip_whitelist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalpermissions",
            options={
                "managed": False,
                "permissions": (
                    ("command.execute_command", "Execute Commands"),
                    ("command.run_script", "Run and Requeue scripts in ScriptQueues"),
                ),
            },
        ),
        migrations.DeleteModel(
            name="CSCAuthorizationRequest",
        ),
    ]
