# Generated by Django 3.2.25 on 2024-07-17 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0017_auto_20240522_2001"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZephyrScaleCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("jira_api_token", models.CharField(max_length=500)),
                ("jira_username", models.CharField(max_length=100)),
                ("zephyr_api_token", models.CharField(max_length=500)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zephyr_scale_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zephyr Scale Credentials",
                "verbose_name_plural": "Zephyr Scale Credentials",
            },
        ),
    ]
