version: "3.7"

services:

  database:
    container_name: love-manager-database
    image: postgres:15.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always

  manager:
    container_name: love-manager-mount
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
    image: love-manager-image-mount
    environment:
      - DB_ENGINE=postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=database
      - DB_PORT=5432
    ports:
    - "8000:8000"
    depends_on:
      - database
    restart: always
    volumes:
      - ../:/usr/src/love
