# Generated by Django 2.2.6 on 2019-10-08 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
