# Generated by Django 2.2.6 on 2019-10-08 19:48

from django.db import migrations
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ("ui_framework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="data",
            field=JSONField(blank=True, null=True),
        ),
    ]
