# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 2.2.9 on 2020-02-11 18:46

from django.db import migrations, models

import ui_framework.models


class Migration(migrations.Migration):
    dependencies = [
        ("ui_framework", "0002_view_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="thumbnail",
            field=models.ImageField(
                default="thumbnails/default.png",
                storage=ui_framework.models.OverwriteStorage(),
                upload_to="thumbnails/",
            ),
        ),
    ]
