# Generated by Django 2.2.9 on 2020-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_framework', '0002_view_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.png', upload_to='thumbnails/'),
        ),
    ]
