# Generated by Django 2.2.6 on 2019-10-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_framework', '0002_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('view_name', models.CharField(blank=True, max_length=20)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_framework.View')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_framework.Workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='views',
            field=models.ManyToManyField(through='ui_framework.WorkspaceView', to='ui_framework.View'),
        ),
    ]
