# Generated by Django 3.1.13 on 2021-10-27 15:57

from django.db import migrations, models

import ui_framework.models


class Migration(migrations.Migration):
    dependencies = [
        ("ui_framework", "0003_view_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ui_framework.models.OverwriteStorage(),
                upload_to="thumbnails/",
            ),
        ),
    ]
