# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.13 on 2021-10-27 15:57

from django.db import migrations, models

import ui_framework.models


class Migration(migrations.Migration):
    dependencies = [
        ("ui_framework", "0003_view_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ui_framework.models.OverwriteStorage(),
                upload_to="thumbnails/",
            ),
        ),
    ]
