# Generated by Django 2.2.6 on 2019-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_framework', '0004_auto_20191008_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspaceview',
            options={'ordering': ('sort_value',)},
        ),
        migrations.AddField(
            model_name='workspaceview',
            name='sort_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceview',
            unique_together={('workspace', 'view')},
        ),
    ]
