# This file is part of LOVE-manager.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.1.14 on 2023-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui_framework", "0004_auto_20211027_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="thumbnail",
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to="thumbnails/"),
        ),
        migrations.AddField(
            model_name="view",
            name="screen",
            field=models.CharField(
                choices=[("4k", "4k"), ("desktop", "desktop"), ("mobile", "mobile")],
                default="desktop",
                max_length=20,
                null=True,
            ),
        ),
    ]
