# Generated by Django 3.1.14 on 2023-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_framework', '0004_auto_20211027_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='screen',
            field=models.CharField(choices=[('4k', '4k'), ('desktop', 'desktop'), ('mobile', 'mobile')], default='desktop', max_length=20, null=True),
        ),
    ]
