"""
Django apps configuration for manager project.

Generated by 'django-admin startproject' using Django 2.1.3.
"""
from django.apps import AppConfig


class ApiConfig(AppConfig):
    """General App config class. Currently defines the name of the app ('api')."""

    name = 'api'
